pipeline {
    agent any
    stages{
        stage ("python version"){
            steps{
                sh 'apt-get update'
                sh 'apt-get upgarde -y'
                sh 'apt-get install python3'
                sh 'python3 --version'
            }
        }
        stage ("Deploy"){
            steps{
                sh 'python3 app.py'
            }
        }
    }
}




