pipeline {
    agent any
    stages{
        stage ("python version"){
            steps{
                sh 'sudo apt update'
                sh 'sudo apt upgarde -y'
                sh 'sudo apt install python3'
                sh 'python3 --version'
            }
        }
        stage ("Deploy"){
            steps{
                sh 'python3 app.py'
            }
        }
    }
}




