pipeline {
    agent any
    stages{
        stage ("python version1"){
            steps{
                sh 'apt update'
                sh 'apt upgarde -y'
                sh 'apt install python3'
                sh 'python3 --version'
            }
        }
        stage ("Deploy"){
            steps{
                sh 'python3 app.py'
            }
        }
    }
}




